### ISSUE TITLE
Move worked examples to separate repo

### ISSUE THREAD

**Issue by rwood-97** [maps-as-data/MapReader#437]
As per suggestion in https://github.com/openjournals/joss-reviews/issues/6434#issuecomment-2136797648:

> I think finally I would recommend having the example notebooks being cloned from a repo that does not also contain the source code so people can clone only them. (you could then use submodules to make this part of the source module to avoid maintaining multiple versions)

Would be good to move worked examples to separate repo.
This could be under LwM org and linked to from the docs/ MapReader repo.

---

Related issues:
- [x] #425

**Comment by kallewesterling** [comment]
I have taken a first stab at this here:

https://github.com/Living-with-machines/MapReader-examples

It is currently private, but what's nice about it is that it's containerised, which means that you could load it like this, after building the image and pushing it to docker hub:

```
docker run -p 8888:8888 kallewesterling/mapreader-examples
```

**Comment by kallewesterling** [comment]
It has a new script called [`download-examples.py`](https://github.com/Living-with-machines/MapReader-examples/blob/main/download-examples.py) which will read [a YAML file](https://github.com/Living-with-machines/MapReader-examples/blob/main/download-examples.yaml) with all the pre-requirements for each notebook, and run the downloader for those particular queries.

**Comment by kallewesterling** [comment]
The Python file has this example of a `download-examples.yaml` file, but here they are for ease of access:

```yaml
- notebook: path/to/notebook.ipynb
  metadata: path/to/metadata.json
  path_save: maps
  zoom: 14
  queries:
    coordinates:
      - -4.33, 55.90
      - -3.25, 51.93
- notebook: path/to/notebook2.ipynb
  metadata: path/to/metadata.json
  path_save: maps
  zoom: 14
  queries:
    polygons:
      latlons:
        - 55.6, -3.5, 56, -2.8
      modes:
        - within
        - intersects
    coordinates:
      - -4.5, 55.4
    lines:
      latlons:
        - xy1: 56.5, -5
          xy2: 57.0, -4.5
    wfs_ids:
      - 12
      - 30
      - 37
      - 38
    string:
      - literal: "Stirling"
      - property: IMAGEURL
        literal: 74487492
```
